name: Webref sync

on:
  workflow_dispatch:
  schedule:
    - cron: 1 1 * * *

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update submodule
        run: |
          git submodule init
          git submodule sync
          git submodule update
          git submodule update --remote

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: "Sync Webref"