name: WebRef Sync

on:
  workflow_dispatch:
  schedule:
    - cron: 1 1 * * 2

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update submodule
        id: submodule
        run: |
          git submodule init
          git submodule sync
          git submodule update
          git submodule update --remote
          echo "sha=$(git submodule status | cut -d ' ' -f1 | cut -c2-)" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          title: "WebRef Sync"
          token: ${{ secrets.BO_PAT }}
          author: bo-homu <bo-homu@users.noreply.github.com>
          commit-message: Sync WebRef to https://github.com/w3c/webref/commit/${{ steps.submodule.outputs.sha }}
          branch: webref-sync
          body: |
            WebRef updated to https://github.com/w3c/webref/commit/${{ steps.submodule.outputs.sha }}
      - name: Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        run: gh pr merge --delete-branch --rebase --auto "${{ steps.cpr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ secrets.BO_PAT }}
